version: "3.8"
services:
  db:
    image: postgres:15
    container_name: socc-db
    restart: always
    environment:
      POSTGRES_DB: socc
      POSTGRES_USER: soccuser
      POSTGRES_PASSWORD: soccpwd
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - socc-net

  backend:
    build:
      context: ./backend
    container_name: socc-backend
    ports:
      - "8070:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/socc
      - SPRING_DATASOURCE_USERNAME=soccuser
      - SPRING_DATASOURCE_PASSWORD=soccpwd
    networks:
      - socc-net

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - socc-net

volumes:
  postgres_data:

networks:
  socc-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16